### PR TITLE
Fix quiz box for homepage on mobile

### PR DESCRIPTION
**Pull request by GLTaylor**

### CODE REVIEW

**Comment by GLTaylor** [comment]
screen shot 2018-09-07 at 11 28 19 am

**Comment by kukurbitacer** [comment]
It might be better to put the@media styling in the home.scss instead of the application.scss. it might be confusing if we look for the styling later on.
Other wise it looks good !
Just one thing, maybe add some margin top to the button so that it has the same spacing between the button, the outline and the selectors. :)

**Comment by GLTaylor** [comment]
ah yes :) so I tried to put it in the home.scss file but it wouldn't work
on local. I'll keep playing.

**Comment by GLTaylor** [comment]
screen shot 2018-09-07 at 5 41 55 pm

**Pull request merged**
